
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    drupal_deployment_home: "deployments/{{ drupal7_stack_name }}"
    
  tasks:

  - name: Determine cluster_pkg_folder
    set_fact:
      cluster_pkg_folder: "{{ inventory_dir | replace(playbook_dir + '/deployments/', '') }}"
    when: cluster_pkg_folder is undefined
    run_once: true

  - debug: var=cluster_pkg_folder
    run_once: true

  - set_fact: drupal_deployment_home="deployments/{{ cluster_pkg_folder }}"

  - name: Ensure the deployment folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ drupal_deployment_home }} ]; then mkdir {{ drupal_deployment_home }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Generate the Drupal manifest
    local_action:
      module: template
      src: templates/drupal.j2
      dest: "{{ drupal_deployment_home }}/drupal.yml"
      mode: 0755
    run_once: true
    become: false

  - name: Generate the CoreOS Tectonic manifest
    local_action:
      module: template
      src: templates/drupal-tectonic-ingress.j2
      dest: "{{ drupal_deployment_home }}/drupal-tectonic-ingress.yml"
      mode: 0755
    run_once: true
    become: false
    

  - name: Ensure the deployment folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ drupal_deployment_home }}/loadtests ]; then mkdir {{ drupal_deployment_home }}/loadtests; fi"
    become: false
    run_once: true
    ignore_errors: true
    
  - name: Generate the medium load tests
    local_action:
      module: template
      src: templates/tests/drupal-load-test-med.j2
      dest: "{{ drupal_deployment_home }}/loadtests/med_load.yml"
      mode: 0755
    run_once: true
    become: false
    
  - name: Generate the heavy load tests
    local_action:
      module: template
      src: templates/tests/drupal-load-test-heavy.j2
      dest: "{{ drupal_deployment_home }}/loadtests/heavy_load.yml"
      mode: 0755
    run_once: true
    become: false
    